"""
DeepFakeLab - Project Structure Setup Script
Automatically creates the directory hierarchy for Phase 1 (EDA) through downstream GAN/VAE/CNN phases.
"""

from pathlib import Path

# Define root project directory
BASE_DIR = Path(__file__).resolve().parent

# Define directory structure
DIRECTORIES = [
    BASE_DIR / "data" / "rvf10k",
    BASE_DIR / "notebooks",
    BASE_DIR / "src",
    BASE_DIR / "outputs" / "figures",
    BASE_DIR / "outputs" / "reports",
]

DIRECTORY_EXPLANATIONS = {
    "data/rvf10k": "Stores the raw, immutable RVF10K benchmark dataset (real and fake faces). Keeping raw data isolated ensures clean data provenance and prevents accidental in-place mutations.",
    "notebooks": "Contains Jupyter notebooks for exploratory data analysis, hypothesis testing, and narrative research documentation in CVPR/ICCV style.",
    "src": "Contains reusable, modular, and testable Python source code (integrity verification, photometric metrics, visualization utilities, config). Prevents notebook code bloat.",
    "outputs/figures": "Dedicated directory for high-DPI publication-grade plots, charts, and inspection grids generated by the analysis.",
    "outputs/reports": "Stores structured textual and tabular reports (e.g. data integrity summaries, statistical findings) for reproducibility and documentation.",
}

def create_project_structure():
    print(f"Initializing DeepFakeLab project structure under: {BASE_DIR}\n")
    for directory in DIRECTORIES:
        directory.mkdir(parents=True, exist_ok=True)
        rel_path = directory.relative_to(BASE_DIR)
        print(f"  [CREATED] {rel_path}")

    print("\nDirectory Purpose & Rationale:")
    for path_str, explanation in DIRECTORY_EXPLANATIONS.items():
        print(f"  - {path_str:<18}: {explanation}")

    print("\nProject structure initialization complete.")

if __name__ == "__main__":
    create_project_structure()
