"""
GAN-VAE Project Structure Setup Script
Automatically creates the centralized data directory and the GAN/ subfolder hierarchy.
"""

from pathlib import Path

# Define root project directory and GAN subfolder
BASE_DIR = Path(__file__).resolve().parent
GAN_DIR = BASE_DIR / "GAN"

# Define directory structure: global data/ at repo root, modules under GAN/
DIRECTORIES = [
    BASE_DIR / "data" / "rvf10k",
    GAN_DIR / "notebooks",
    GAN_DIR / "src",
    GAN_DIR / "outputs" / "figures",
    GAN_DIR / "outputs" / "reports",
]

DIRECTORY_EXPLANATIONS = {
    "data/rvf10k": "Global repository-level dataset repository (real and fake faces, car datasets, etc.). Keeping data centralized allows sharing across GAN, VAE, and other custom models.",
    "GAN/notebooks": "Contains Jupyter notebooks for exploratory data analysis, hypothesis testing, and narrative research documentation in CVPR/ICCV style.",
    "GAN/src": "Contains reusable, modular, and testable Python source code (integrity verification, photometric metrics, visualization utilities, config). Prevents notebook code bloat.",
    "GAN/outputs/figures": "Dedicated directory for high-DPI publication-grade plots, charts, and inspection grids generated by the analysis.",
    "GAN/outputs/reports": "Stores structured textual and tabular reports (e.g. data integrity summaries, statistical findings) for reproducibility and documentation.",
}

def create_project_structure():
    print(f"Initializing GAN-VAE project structure under: {BASE_DIR}\n")
    for directory in DIRECTORIES:
        directory.mkdir(parents=True, exist_ok=True)
        rel_path = directory.relative_to(BASE_DIR)
        print(f"  [CREATED] {rel_path}")

    print("\nDirectory Purpose & Rationale:")
    for path_str, explanation in DIRECTORY_EXPLANATIONS.items():
        print(f"  - {path_str:<20}: {explanation}")

    print("\nProject structure initialization complete.")

if __name__ == "__main__":
    create_project_structure()
